# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eb7c27fde101fe51a03b0c718510cdfa400d0d6a79ecd1c6e08b9bb52a386df90f2a7b82310abccd11be51e558a5af89dd03860ca02163b6ab2bd4f7e7c5c39

test:
  secret_key_base: 6201f6e81f3826a8ed57b81330282b2c5f322e4d78b6b1d6abc40781aa2c58e0217a65739c53b3b695527bfb71ef19b7097db94a71e556c69881f36caa574bd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
